### ISSUE TITLE
PA Flow for CST

### ISSUE THREAD

**Issue by plattasia** [akporzondek/adoption_hub#1]
The Import of the PA flow does not allow to pick Excel connection. I have added both but it does not like either one. 

![image](https://user-images.githubusercontent.com/39997638/115582680-32255180-a297-11eb-81af-5e9c08d6a1ba.png)
![image](https://user-images.githubusercontent.com/39997638/115582713-39e4f600-a297-11eb-8f7b-38c624c058e2.png)

**Comment by akporzondek** [comment]
Hi, the default Flow components we were using were deprecated. We have added a new Flow package with components that are working now with Excel and OneDrive for Business. 

https://github.com/akporzondek/adoption_hub/commit/1347e37a1458aefb9c205c5edcf0adc511056544
